project:
  type: website

website:
  title: "Noëlle S. Foster Feliciano, Ph.D."
  #site-url: 
  description: "This is where I think spontaneous thoughts."
  navbar:
    right:
      - archive.qmd
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/noellesfosterphd/
      - icon: mastodon
        href: https://h-net.social/@noellesfoster
format:
  html:
    theme: lumen
    css: styles.css

editor: visual

