project:
  type: website

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/nsfphd
      - icon: mastodon
        href: https://mastodon.social/@noelletakespics
format:
  html:
    theme: lumen
    css: styles.css

editor: visual

