project:
  type: website

website:
  title: "Noëlle S. Foster Feliciano, Ph.D."
  #site-url: 
  description: "This is where I think spontaneous thoughts."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/nsfphd
      - icon: mastodon
        href: https://mastodon.social/@noelletakespics
format:
  html:
    theme: lumen
    css: styles.css

editor: visual

